### ISSUE TITLE
Use monotonic time for benchmark timing

### ISSUE THREAD

**Issue by alanbernstein** [pilosa/tools#48]
`time.Now()` returns real time, which can jump occasionally. https://github.com/gavv/monotime, for example, provides a monotonic `Now()` function, which is preferable for timing measurements.

**Comment by jaffee** [comment]
Seems like it is in 1.9 - basically, time.Now() will internally include both wall time and monotonic information, and will use whichever is more appropriate for a given situation - so doing `time.Sub` or `time.Since` will use the monotonic time, and we won't need to update our code at all.

**Comment by jaffee** [comment]
I'm gonna go ahead and close this - feel free to re-open if there  are still concerns.
