### ISSUE TITLE
apophenia loops forever in Zipf.Nth

### ISSUE THREAD

**Issue by jaffee** [pilosa/tools#76]
Run `imagine` with the following config. Notice that it hangs.
```
densityscale = 2097152
version = "1.0"
[indexes.inf]
columns = 10000
fields = [
  { name = "ting", type="mutex", max=2, density=0.9, valueRule="zipf", cache = "lru" },
]
[[workloads]]
[[workloads.batches]]
description = "initial"
tasks = [
  { index = "inf", field = "ting" },
]
```

I tracked this into apophenia/zipf.go (the `for` loop in the `Nth` method). Setting zipfV and zipfS (to e.g. 3.0 and 1.1) in the config for the field fixes this, but we should probably:
(a) default them to reasonable values, and
(b) error at some point if they are set to values which would infinitely loop.

or, I guess, potentially there is an actual bug that causes the infinite loop with the default values.

**Comment by seebs** [comment]
It looks like this is a straightforward bug -- there's invalid inputs (q must be > 1, v >= 1), and NewZipf never actually checked for error conditions. Have a patch.
